server:
  port: 8888 # 服务端口
eureka:
  instance:
    hostname: localhost # 设置主机名  
    # 为了保证服务的快速发现和注销  
    leaseRenewalIntervalInSeconds: 1  #心跳间隔时间1s
    leaseExpirationDurationInSeconds: 2  #连续2s未响应时将服务注销
  client:
    registerWithEureka: false # 是否向 Eureka 注册服务。该应用为服务注册中心，不需要自注册，设置为 false
    fetchRegistry: false      # 是否检索服务。该应用为服务注册中心，职责为注册和发现服务，无需检索服务，设置为 false
  server:
    waitTimeInMsWhenSyncEmpty: 5 # 设置同步为空时的等待时间。默认 5 * MINUTES
    enableSelfPreservation: false # 在测试环境我们可以关掉Eureka的自我保护机制，否则会提示： EMERGENCY! EUREKA MAY BE INCORRECTLY CLAIMING INSTANCES ARE UP WHEN THEY'RE NOT. RENEWALS ARE LESSER THAN THRESHOLD AND HENCE THE INSTANCES ARE NOT BEING EXPIRED JUST TO BE SAFE.